#!/bin/bash
# Script de démarrage rapide du projet BadWallet API & Payment Service

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║       BADWALLET API & PAYMENT SERVICE - STARTUP SCRIPT        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 STATUS: ✅ PROJET COMPLET"
echo ""

echo "🏗️  ARCHITECTURE:"
echo "   ├─ BadWallet API"
echo "   │  ├─ Port: 8080"
echo "   │  ├─ Jar: target/badwallet-api-0.0.1-SNAPSHOT.jar"
echo "   │  ├─ DB: H2 (badwalletdb)"
echo "   │  └─ Endpoints: 14 (CRUD + Transactions + Factures)"
echo "   │"
echo "   └─ Payment Service"
echo "      ├─ Port: 8081"
echo "      ├─ Jar: target/payment-service-0.0.1-SNAPSHOT.jar"
echo "      ├─ DB: H2 (paymentdb)"
echo "      └─ Endpoints: 5 (Consultation + Paiement Factures)"
echo ""

echo "📊 GIT FLOW:"
echo "   ├─ main (branche principale)"
echo "   ├─ develop (branche d'intégration)"
echo "   │"
echo "   ├─ BADWALLET API - Feature branches:"
echo "   │  ├─ feature/wallet-creation"
echo "   │  ├─ feature/wallet-list"
echo "   │  ├─ feature/wallet-balance"
echo "   │  ├─ feature/wallet-deposit"
echo "   │  ├─ feature/wallet-withdraw"
echo "   │  ├─ feature/wallet-transfer"
echo "   │  ├─ feature/wallet-seeder"
echo "   │  ├─ feature/payment-services (proxy)"
echo "   │  ├─ feature/facture-payment"
echo "   │  ├─ feature/facture-bulk-payment"
echo "   │  └─ feature/http-test-file"
echo "   │"
echo "   └─ PAYMENT SERVICE - Feature branches:"
echo "      ├─ feature/factures-seeder"
echo "      ├─ feature/factures-list"
echo "      ├─ feature/factures-by-period"
echo "      ├─ feature/factures-pay-current"
echo "      └─ feature/factures-pay-by-ref"
echo ""

echo "🚀 POUR LANCER LES SERVICES:"
echo ""
echo "   # Terminal 1 - BadWallet API"
echo "   cd c:\\badwallet-api"
echo "   java -jar target/badwallet-api-0.0.1-SNAPSHOT.jar"
echo ""
echo "   # Terminal 2 - Payment Service"
echo "   cd c:\\payment-service"
echo "   java -jar target/payment-service-0.0.1-SNAPSHOT.jar"
echo ""

echo "🧪 POUR TESTER LES ENDPOINTS:"
echo ""
echo "   1. Installer extension VS Code: REST Client (Huachao Mao)"
echo "   2. Ouvrir c:\\badwallet-api\\src\\test.http"
echo "   3. Cliquer 'Send Request' sur chaque endpoint"
echo ""

echo "📚 DOCUMENTATION:"
echo "   ├─ README_TESTING.md    - Guide complet de test"
echo "   ├─ RAPPORT_FINAL.md     - Vue d'ensemble du projet"
echo "   └─ src/test.http        - Suite de tests HTTP"
echo ""

echo "🔗 ACCÈS AUX SERVICES:"
echo "   ├─ BadWallet API: http://localhost:8080"
echo "   ├─ Payment Service: http://localhost:8081"
echo "   ├─ H2 Console BadWallet: http://localhost:8080/h2-console"
echo "   └─ H2 Console Payment: http://localhost:8081/h2-console"
echo ""

echo "✅ ENDPOINTS DISPONIBLES:"
echo "   BadWallet API: 14 endpoints"
echo "   Payment Service: 5 endpoints"
echo "   TOTAL: 19 endpoints"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                 ✅ PROJET PRÊT POUR LE TEST                   ║"
echo "╚════════════════════════════════════════════════════════════════╝"
